title: Piráti
baseurl:
default_locale: "cs"
permalink: pretty
markdown: kramdown
gems:
  - jekyll-sitemap
  - i18n
# paginate: 7
# paginate_path: "/clanky/:num/"


exclude: [README.md, TODO.md, LICENSE, Gemfile, Gemfile.lock]

# own confs
facebookurl: https://www.facebook.com/ceska.piratska.strana

# see. best practices DOs and DONTs for details about following section
# http://www.elegantthemes.com/blog/tips-tricks/best-practices-for-using-categories-and-tags-in-wordpress
avail_tags: transparence, it, kultura, sport, jordan, krizikac, web
avail_cats: AKCE, JEDNANI, CLANKY
avail_filecats: SMLOUVY, ZAPISY, VYKRESY, GRAFIKA
